#!/usr/bin/env python3
"""Generate a compact CP932 (Shift-JIS) -> Unicode table for ECL text.

TH06 ECL files store strings as raw Shift-JIS bytes. The example converts
them to UTF-8 at runtime; this script emits the lookup table used by that
conversion so it works on every platform (the Windows MultiByteToWideChar
path is not available on wasm).

Run: python tools/gen_shift_jis_table.py > examples/th06/src/shift_jis_table.h
"""

import codecs

LEADS = list(range(0x81, 0xA0)) + list(range(0xE0, 0xEB)) + [0xED, 0xEE] + list(range(0xFA, 0xFD))
TRAILS = list(range(0x40, 0x7F)) + list(range(0x80, 0xFD))

def lead_index(byte):
    if 0x81 <= byte <= 0x9F:
        return byte - 0x81
    if 0xE0 <= byte <= 0xEA:
        return 31 + (byte - 0xE0)
    if byte == 0xED:
        return 31 + 11
    if byte == 0xEE:
        return 31 + 12
    if 0xFA <= byte <= 0xFC:
        return 31 + 13 + (byte - 0xFA)
    return -1

def trail_index(byte):
    if 0x40 <= byte <= 0x7E:
        return byte - 0x40
    if 0x80 <= byte <= 0xFC:
        return 63 + (byte - 0x80)
    return -1

table = [0] * (len(LEADS) * len(TRAILS))
for lead in LEADS:
    for trail in TRAILS:
        try:
            codepoint = ord(codecs.decode(bytes([lead, trail]), "shift_jis"))
        except UnicodeDecodeError:
            codepoint = 0
        table[lead_index(lead) * len(TRAILS) + trail_index(trail)] = codepoint

print("// Generated by tools/gen_shift_jis_table.py -- do not edit manually.")
print("#pragma once")
print("#include <cstdint>")
print("")
print("// Compact CP932 double-byte to Unicode mapping used by eclTextToUtf8.")
print("// Indexed by [leadIndex * 188 + trailIndex]; zero marks undefined pairs.")
print(f"inline constexpr std::uint16_t kShiftJisTable[{len(LEADS) * len(TRAILS)}] = {{")
for row in range(0, len(table), 16):
    chunk = table[row:row + 16]
    print("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
print("};")